[package]
name = "cellcast_python"
version = "0.3.0"
authors = ["cellcast developers"]
edition = "2024"
license = "Unlicense OR MIT"
repository = "https://github.com/uw-loci/cellcast"
readme = "README.md"

[lib]
name = "cellcast"
crate-type = ["cdylib"]
doc = false

[dependencies]
cellcast = { path = "../cellcast" }
imgal = "0.3.1"
pyo3 = { version = "0.29", features = ["extension-module", "abi3-py38", "generate-import-lib"] }
numpy = "0.29"

[lints.clippy]
too_many_arguments = "allow"
